BINARY_NAME=czwrMailing

test:
	go test .\internal\dbcontext\inmemoryctx\ -v

swag:
	swag init -d .\internal\app\ -o .\doc\ -g app.go --parseDependency

build:
	go build -o bin\${BINARY_NAME}.exe .\cmd\app\main.go
run:
	bin\${BINARY_NAME}.exe -config .\bin\config.yml

build_and_run: test swag build run

build_docker: test swag
	docker build --tag czwr-mailing .