name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  build:
      name: build
      runs-on: ubuntu-latest
      needs: golangci
      steps:
        - uses: actions/checkout@v2
        - name: check docker
          run: docker version 
       
        - name: ls -a
          run: ls -a

        - name: cat MakeFile
          run: cat MakeFile   

        - name: build docker file 
          run: docker build --tag czwr-mailing .

